{
 "title": "FLASK",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "garbage collection",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "request duraction seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(flask_http_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "request total",
   "type": "stat",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "flask_http_request_total", "legendFormat": "__auto" }
   ]
  }
 ]
}